java:
  applicationPort: 8485
  environment:
    # db
    LETTER_TRACKING_DB_NAME: letter_tracking
    LETTER_TRACKING_DB_HOST: ${SERVICE_NAME}-postgresql
    LETTER_TRACKING_DB_PORT: "5432"
    LETTER_TRACKING_DB_USER_NAME: letterservice
    LETTER_TRACKING_DB_PASSWORD: letterpassword
    # db - migration
    FLYWAY_URL: "jdbc:postgresql://${SERVICE_NAME}-postgresql:5432/letter_tracking"
    FLYWAY_NOOP_STRATEGY: "false"
    # encryption
    ENCRYPTION_ENABLED: "false"
    ENCRYPTION_PUBLIC_KEY: ""
    # schedules
    SCHEDULING_ENABLED: "true"
    # inherited
    LOGBACK_REQUIRE_ALERT_LEVEL: "false"
    LOGBACK_REQUIRE_ERROR_CODE: "false"
    S2S_NAME: "send_letter_tests"
    S2S_URL: "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
    FTP_HOSTNAME: "cmseft.services.xerox.com"
    FTP_PORT: "22"
    FTP_FINGERPRINT: "SHA256:3tX3DIkqd1Loz2alHfnt+qjHocfxk0YUOZHlnf9Zgdk"
    FTP_TARGET_FOLDER: "TO_XEROX"
    FTP_REPORTS_FOLDER: "FROM_XEROX"
    FTP_DOWNTIME_FROM: "23:58"
    FTP_DOWNTIME_TO: "23:59"
    # mails
    SPRING_MAIL_HOST: "false"
  keyVaults:
    rpe-send-letter:
      resourceGroup: rpe-send-letter-service
      secrets:
        - ftp-user
        - ftp-private-key
        - ftp-public-key
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}

postgresql:
  postgresqlUsername: letterservice
  postgresqlPassword: letterpassword
  postgresqlDatabase: letter_tracking
  service:
    port: 5432
  persistence:
    enabled: false
tags:
  postgresql-pod: true
